[2024-01-23 22:36:31,495][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-23-22-36-31-493849.log
[2024-01-23 22:36:43,519][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    img_det = np.copy(img)
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 22:36:43,520][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-01-23 22:36:53,813][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    # print("det 的长度为 %d" % len(det))
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 22:36:53,815][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-01-23 22:37:03,563][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    # print("det 的长度为 %d" % len(det))
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-23 22:37:03,563][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-01-23 22:37:12,268][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    # print("det 的长度为 %d" % len(det))
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:37:12,269][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-01-23 22:37:21,494][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    # print("det 的长度为 %d" % len(det))
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 22:37:21,495][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-01-23 22:37:31,577][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    # print("det 的长度为 %d" % len(det))
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:37:31,579][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-01-23 22:37:40,396][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    # print("det 的长度为 %d" % len(det))
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-23 22:37:40,398][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-01-23 22:37:48,979][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    # print("det 的长度为 %d" % len(det))
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:37:48,980][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-01-23 22:37:56,829][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    # print("det 的长度为 %d" % len(det))
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:37:56,830][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-01-23 22:37:56,833][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:38:05,675][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    # TODO weights与imgsz与cams-ratio都是每个相机分别的，lazy_threshold只有一个
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    p = Path(p)
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-23 22:38:05,676][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-01-23 22:38:05,680][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:38:15,348][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    # TODO weights与imgsz与cams-ratio都是每个相机分别的，lazy_threshold只有一个
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    p = Path(p)
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:38:15,349][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-01-23 22:38:15,352][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-23 22:38:24,371][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 907, in profile
    # TODO weights与imgsz与cams-ratio都是每个相机分别的，lazy_threshold只有一个
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 608, in run_mtmc
    p = Path(p)
  File "<__array_function__ internals>", line 200, in copy
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/numpy/lib/function_base.py", line 960, in copy
    return array(a, order=order, subok=subok, copy=True)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:38:24,372][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-01-23 22:38:24,374][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
