[2024-01-24 22:51:47,491][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-24-22-51-47-490947.log
[2024-01-24 23:30:42,134][0][INFO][generic_smbo.py:295] Iter 1, objectives: [0.8265547034737056, 0.06058683610624737].
[2024-01-24 23:54:48,488][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 929, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 413, in mot_metrics
    f1_score = 200 * recall * precision / (precision + recall)
ZeroDivisionError: float division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-24 23:54:48,489][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
