[2024-02-22 19:14:23,045][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-02-22-19-14-23-044389.log
[2024-02-22 19:14:23,313][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:23,526][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:23,742][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:23,951][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:24,186][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:24,404][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:24,596][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:24,784][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:24,968][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:25,153][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:25,337][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:25,541][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:25,755][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:25,963][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:26,184][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:26,392][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:26,593][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:26,811][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:27,025][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:27,235][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:27,452][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:27,662][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:27,878][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:28,080][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:28,291][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:28,493][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:28,697][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:28,922][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:29,135][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:29,348][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:29,561][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:29,755][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:29,974][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:30,192][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:30,406][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:30,607][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:30,790][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:30,980][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:31,168][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:31,389][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:31,621][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:31,851][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:32,080][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:32,300][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:32,534][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:32,760][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:32,964][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:33,175][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:33,390][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:33,599][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:33,784][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:33,991][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:34,209][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:34,450][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:34,675][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:34,886][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:35,119][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:35,342][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:35,564][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:35,775][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:35,958][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:36,148][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:36,370][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:36,604][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:36,646][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,646][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-02-22 19:14:36,647][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,648][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-02-22 19:14:36,649][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,649][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-02-22 19:14:36,650][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,650][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-02-22 19:14:36,651][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,652][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,652][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:36,652][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-02-22 19:14:36,653][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,654][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,654][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:36,654][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-02-22 19:14:36,655][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,655][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,656][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:36,656][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-02-22 19:14:36,656][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,657][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,657][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:36,657][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-02-22 19:14:36,658][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,658][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,659][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:36,659][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-02-22 19:14:36,661][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,662][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,662][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-02-22 19:14:36,663][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,664][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,664][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-02-22 19:14:36,665][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,666][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,666][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-02-22 19:14:36,666][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,667][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,668][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-02-22 19:14:36,669][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,670][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,670][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-02-22 19:14:36,671][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,672][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,672][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-02-22 19:14:36,673][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:14:36,674][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,674][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-02-22 19:14:36,675][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,676][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,677][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-02-22 19:14:36,677][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,679][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,679][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-02-22 19:14:36,680][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,681][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,681][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-02-22 19:14:36,682][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,683][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,683][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-02-22 19:14:36,684][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,685][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,685][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-02-22 19:14:36,686][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,687][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,687][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-02-22 19:14:36,688][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,690][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,690][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-02-22 19:14:36,691][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,692][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,692][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-02-22 19:14:36,693][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,694][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,695][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-02-22 19:14:36,695][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,697][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,697][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-02-22 19:14:36,698][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,699][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,699][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-02-22 19:14:36,700][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,702][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,702][0][INFO][generic_smbo.py:295] Iter 28, objectives: [inf, inf].
[2024-02-22 19:14:36,703][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,704][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,704][0][INFO][generic_smbo.py:295] Iter 29, objectives: [inf, inf].
[2024-02-22 19:14:36,705][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,706][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,707][0][INFO][generic_smbo.py:295] Iter 30, objectives: [inf, inf].
[2024-02-22 19:14:36,707][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,709][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,709][0][INFO][generic_smbo.py:295] Iter 31, objectives: [inf, inf].
[2024-02-22 19:14:36,710][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,712][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,713][0][INFO][generic_smbo.py:295] Iter 32, objectives: [inf, inf].
[2024-02-22 19:14:36,714][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,716][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,717][0][INFO][generic_smbo.py:295] Iter 33, objectives: [inf, inf].
[2024-02-22 19:14:36,717][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,720][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,720][0][INFO][generic_smbo.py:295] Iter 34, objectives: [inf, inf].
[2024-02-22 19:14:36,721][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,724][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,724][0][INFO][generic_smbo.py:295] Iter 35, objectives: [inf, inf].
[2024-02-22 19:14:36,725][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,728][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,729][0][INFO][generic_smbo.py:295] Iter 36, objectives: [inf, inf].
[2024-02-22 19:14:36,729][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,731][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:36,731][0][INFO][generic_smbo.py:295] Iter 37, objectives: [inf, inf].
[2024-02-22 19:14:36,732][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,733][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,734][0][INFO][generic_smbo.py:295] Iter 38, objectives: [inf, inf].
[2024-02-22 19:14:36,734][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,737][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,738][0][INFO][generic_smbo.py:295] Iter 39, objectives: [inf, inf].
[2024-02-22 19:14:36,738][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,740][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,741][0][INFO][generic_smbo.py:295] Iter 40, objectives: [inf, inf].
[2024-02-22 19:14:36,741][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,743][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:36,744][0][INFO][generic_smbo.py:295] Iter 41, objectives: [inf, inf].
[2024-02-22 19:14:36,745][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:36,961][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:36,961][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,962][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:36,962][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:36,962][0][INFO][generic_smbo.py:295] Iter 42, objectives: [inf, inf].
[2024-02-22 19:14:36,963][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:37,175][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:37,176][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:37,176][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:37,177][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:37,177][0][INFO][generic_smbo.py:295] Iter 43, objectives: [inf, inf].
[2024-02-22 19:14:37,178][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:37,390][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:37,390][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:37,391][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:37,391][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:37,391][0][INFO][generic_smbo.py:295] Iter 44, objectives: [inf, inf].
[2024-02-22 19:14:37,392][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:37,593][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:37,593][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:37,594][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:37,594][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:37,594][0][INFO][generic_smbo.py:295] Iter 45, objectives: [inf, inf].
[2024-02-22 19:14:37,595][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:37,796][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:37,796][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:37,797][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:37,797][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:37,797][0][INFO][generic_smbo.py:295] Iter 46, objectives: [inf, inf].
[2024-02-22 19:14:37,798][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:38,002][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:38,002][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:38,003][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:14:38,004][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:38,004][0][INFO][generic_smbo.py:295] Iter 47, objectives: [inf, inf].
[2024-02-22 19:14:38,005][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:14:38,220][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:38,220][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:38,221][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:38,221][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:38,221][0][INFO][generic_smbo.py:295] Iter 48, objectives: [inf, inf].
[2024-02-22 19:14:38,222][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:14:38,447][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:38,447][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:38,448][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:14:38,448][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:38,449][0][INFO][generic_smbo.py:295] Iter 49, objectives: [inf, inf].
[2024-02-22 19:14:38,449][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:14:38,661][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:14:38,661][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:38,662][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
TypeError: profile() missing 1 required positional argument: 'lazy_threshold_'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:14:38,662][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:14:38,663][0][INFO][generic_smbo.py:295] Iter 50, objectives: [inf, inf].
[2024-02-22 19:14:38,676][0][WARNING][history.py:651] No feasible observations! Return empty pareto.
