[2024-03-05 13:58:51,880][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-03-05-13-58-51-879954.log
[2024-03-05 13:58:52,172][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:52,406][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:52,657][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:52,903][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:53,120][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:53,349][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:53,573][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:53,768][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:54,010][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:54,257][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:54,461][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:54,724][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:54,980][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:55,240][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:55,458][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:55,664][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:55,901][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:56,152][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:56,344][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:56,552][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:56,747][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:56,982][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:57,177][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:57,382][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:57,574][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:57,760][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:57,960][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:58,228][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:58,473][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:58,689][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:58,912][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:59,137][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:59,368][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:59,610][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:58:59,833][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:00,070][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:00,338][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:00,579][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:00,842][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:01,147][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:01,449][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:01,679][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:01,868][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:02,084][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:02,347][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:02,609][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:02,864][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:03,120][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:03,339][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:03,520][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:03,750][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:03,985][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-03-05 13:59:09,982][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.77 GiB total capacity; 1.73 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-03-05 13:59:09,983][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-03-05 13:59:10,753][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.77 GiB total capacity; 1.94 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5x.pt',
  'resolution_camera': '1280',
})

[2024-03-05 13:59:10,754][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-03-05 13:59:11,451][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.77 GiB total capacity; 1.73 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-03-05 13:59:11,452][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-03-05 13:59:11,453][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-03-05 13:59:11,882][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.77 GiB total capacity; 1.94 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5x.pt',
  'resolution_camera': '640',
})

[2024-03-05 13:59:11,882][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-03-05 13:59:11,942][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-05 13:59:12,467][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 9.77 GiB total capacity; 1.79 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-03-05 13:59:12,467][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-03-05 13:59:12,468][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-03-05 13:59:12,980][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 9.77 GiB total capacity; 1.79 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-03-05 13:59:12,981][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-03-05 13:59:12,982][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-05 13:59:13,296][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.77 GiB total capacity; 1.94 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5x.pt',
  'resolution_camera': '640',
})

[2024-03-05 13:59:13,297][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-03-05 13:59:13,297][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-03-05 13:59:13,844][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 9.77 GiB total capacity; 1.79 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-03-05 13:59:13,844][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-03-05 13:59:13,845][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-05 13:59:14,231][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 787, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(target_cam_index=target_cam_, cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 480, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.77 GiB total capacity; 1.94 MiB already allocated; 3.62 MiB free; 2.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5x.pt',
  'resolution_camera': '320',
})

[2024-03-05 13:59:14,232][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-03-05 13:59:14,233][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
